### ISSUE TITLE
Compress middleware's ResponseWriter does not implement CloseNotifier

### ISSUE THREAD

**Issue by nkovacs** [pressly/chi#152]
I tried to use both `middleware.CloseNotifier` and `middleware.DefaultCompress`, but this caused a panic because `maybeCompressResponseWriter` does not implement `http.CloseNotifier`.

**Comment by pkieltyka** [comment]
@nkovacs what version of Go?

**Comment by pkieltyka** [comment]
and http1 or http2?

**Comment by nkovacs** [comment]
1.7, http1 (but should apply to http2 too).

I think if I switch the order of the middlewares, it'll work, because CloseNotifier will get the original ResponseWriter.

**Comment by nkovacs** [comment]
Ok, so doing this causes a panic:

```
r.use(middleware.DefaultCompress)
r.use(middleware.CloseNotify)
```

But this doesn't:

```
r.use(middleware.CloseNotify)
r.use(middleware.DefaultCompress)
```

On a related not, it would be nice to have a dummy middleware.CloseNotify for go 1.8, so that this code also compiles on go 1.8.

**Comment by pkieltyka** [comment]
@nkovacs can you try again? PR #154 recently merged should fix this as well

**Comment by nkovacs** [comment]
Yes, that fixes it, thanks.
